FROM n8nio/n8n

# Define o diretório de trabalho
WORKDIR /home/node

# Copia as variáveis de ambiente (se quiser embutir, opcional)
# COPY .env .env

# Expõe a porta usada pelo n8n
EXPOSE 5678

# Comando para iniciar o n8n
CMD ["n8n"]

